// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwvsvjlrvhthrtgagvtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dnN2amxydmh0aHJ0Z2FndnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzMwNTQsImV4cCI6MjA1NzUwOTA1NH0.BzcD7l8E1tK4MQRhq2c-VA1QLOV5oNm91DOomzQQCck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);